"""Seed data for Mi Lugar module — 17 estados + 49 proyectos + config."""
from decimal import Decimal

# ─── IDs de estados (BigInt, extraídos del boceto HTML) ───────────────────────
E_SIN_INICIAR = 1
E_NOTA_MCYM = 2
E_PASE_SEC_GESTION = 3
E_INTERVENCION_INFRA = 4
E_INFORME_PREFACT = 1780946950156
E_DIR_REG_OBRAS = 1780946983131
E_PARA_EVALUACION = 1780969315323
E_ADM_DGV_NP = 1780946997043
E_LEGALES_RESOLUCION = 1780947046770
E_LEGALES_MCYM = 1780947103658
E_ADM_DGV_OC = 1780947119226
E_TC = 1780947254281
E_MIN_ECONOMIA = 1780947581767
E_SEC_GOBERNACION = 1780947614565
E_CONSEJO_TASACIONES = 1780947663757
E_COMPLETADO = 1780947777818
E_PROCURACION = 1780969315322

ESTADOS_SEED = [
    {"id": E_SIN_INICIAR,       "label": "Sin Iniciar",                                                                    "bg": "#ECEFF1", "text_color": "#455A64", "orden": 1},
    {"id": E_NOTA_MCYM,         "label": "Nota del Municipio al MCyM",                                                     "bg": "#FFF3CD", "text_color": "#856404", "orden": 2},
    {"id": E_PASE_SEC_GESTION,  "label": "Pase a la Sec de Gestion y Vinculacion de Infra - LUIS MOLINARI",               "bg": "#DBEAFE", "text_color": "#1E40AF", "orden": 3},
    {"id": E_INTERVENCION_INFRA,"label": "Intervencion del Minst de Infra y Serv Pub",                                     "bg": "#D4EDDA", "text_color": "#155724", "orden": 4},
    {"id": E_INFORME_PREFACT,   "label": "Informe de Prefactibilidad Sec de Planificacion Energetica MIySP",              "bg": "#EDE7F6", "text_color": "#4527A0", "orden": 5},
    {"id": E_DIR_REG_OBRAS,     "label": "Dir de Reg de Obras y Proyectos, Informe, valor Fiscal + 30%",                  "bg": "#FFF3E0", "text_color": "#E65100", "orden": 6},
    {"id": E_PARA_EVALUACION,   "label": "Para Evaluacion si va por Tasacion o con valuacion + el 30%",                   "bg": "#FFE5D0", "text_color": "#8B3A00", "orden": 7},
    {"id": E_ADM_DGV_NP,        "label": "Administracion DGV para NP",                                                    "bg": "#E0F2F1", "text_color": "#00695C", "orden": 8},
    {"id": E_LEGALES_RESOLUCION,"label": "Legales para Proyecto de Resolucion",                                            "bg": "#FCE4EC", "text_color": "#880E4F", "orden": 9},
    {"id": E_LEGALES_MCYM,      "label": "Legales del MCyM para Dictamen + Resolucion",                                   "bg": "#FFEBEE", "text_color": "#B71C1C", "orden": 10},
    {"id": E_ADM_DGV_OC,        "label": "Administracion DGV para OC",                                                    "bg": "#E0F7FA", "text_color": "#006064", "orden": 11},
    {"id": E_TC,                "label": "TC",                                                                             "bg": "#E8EAF6", "text_color": "#1A237E", "orden": 12},
    {"id": E_MIN_ECONOMIA,      "label": "MINISTERIO DE ECONOMIA Y GESTION PUBLICA",                                      "bg": "#E3F2FD", "text_color": "#0D47A1", "orden": 13},
    {"id": E_SEC_GOBERNACION,   "label": "SECRETARIA GENERAL DE LA GOBERNACION",                                          "bg": "#F3E5F5", "text_color": "#6A1B9A", "orden": 14},
    {"id": E_CONSEJO_TASACIONES,"label": "CONSEJO GENERAL DE TASACIONES",                                                 "bg": "#EFEBE9", "text_color": "#4E342E", "orden": 15},
    {"id": E_COMPLETADO,        "label": "COMPLETADO",                                                                     "bg": "#C8E6C9", "text_color": "#1B5E20", "orden": 16},
    {"id": E_PROCURACION,       "label": "PROCURACION",                                                                    "bg": "#FFF8E1", "text_color": "#E65100", "orden": 17},
]

CONFIG_SEED = {
    "tipo_cambio": Decimal("1450"),
    "usd_por_lote": Decimal("10000"),
    "lotes_por_ha": Decimal("25"),
}

# ─── Proyectos (49 registros extraídos del boceto) ────────────────────────────
# Campos: tipo, nombre, localidad_nombre, expediente, superficie, lotes,
#         ejuridico, etecnico, efinanciero, monto, valor_fiscal,
#         infra_sin_nexos, costo_nexos, convenio_unc, costo_total_infra, obs,
#         geo_puntos: list[{"lat", "lng"}]

PROYECTOS_SEED = [
    # ── EXPROPIACIONES (21) ──────────────────────────────────────────────────
    {
        "tipo": "exp",
        "nombre": "MALVINAS ARGENTINAS",
        "localidad_nombre": "Malvinas Argentinas",
        "expediente": "0135-044535/2026",
        "superficie": Decimal("153.54"),
        "lotes": 2100,
        "ejuridico": E_CONSEJO_TASACIONES,
        "etecnico": E_COMPLETADO,
        "efinanciero": E_CONSEJO_TASACIONES,
        "monto": Decimal("45559769973.93"),
        "valor_fiscal": Decimal("1629923801.00"),
        "infra_sin_nexos": Decimal("30450000000.00"),
        "costo_nexos": Decimal("12425288407.63"),
        "convenio_unc": Decimal("565580625.00"),
        "costo_total_infra": Decimal("45559769973.93"),
        "obs": "8/6 CUERPO TECNICO DEL CONSEJO GENERAL DE TASACIONES",
        "geo_puntos": [],  # short URL — no coords available
    },
    {
        "tipo": "exp",
        "nombre": "ESTACION JUAREZ CELMAN",
        "localidad_nombre": "Estacion Juarez Celman",
        "expediente": "0404-001192/2026",
        "superficie": Decimal("69.19"),
        "lotes": 1484,
        "ejuridico": E_COMPLETADO,
        "etecnico": E_COMPLETADO,
        "efinanciero": E_MIN_ECONOMIA,
        "monto": Decimal("33811009156.78"),
        "valor_fiscal": Decimal("2238814197.52"),
        "infra_sin_nexos": Decimal("21518000000.00"),
        "costo_nexos": Decimal("9087377853.00"),
        "convenio_unc": Decimal("295172847.00"),
        "costo_total_infra": Decimal("33811009156.78"),
        "obs": "28/7 vuelve del TC visado\nPara Deposito",
        "geo_puntos": [
            {"lat": Decimal("-31.292807"), "lng": Decimal("-64.177675")},
            {"lat": Decimal("-31.289985"), "lng": Decimal("-64.179777")},
        ],
    },
    {
        "tipo": "exp",
        "nombre": "ESTACION GRAL. PAZ",
        "localidad_nombre": "Estacion General Paz",
        "expediente": None,
        "superficie": Decimal("18.7582"),
        "lotes": 562,
        "ejuridico": E_SIN_INICIAR,
        "etecnico": E_DIR_REG_OBRAS,
        "efinanciero": E_SIN_INICIAR,
        "monto": Decimal("8508237937.83"),
        "valor_fiscal": Decimal("276336875.25"),
        "infra_sin_nexos": Decimal("8149000000.00"),
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": Decimal("8508237937.83"),
        "obs": "CON INFORME + EL 30% PARA MANDAR A SERV PUB. INTENDENTE DEBE INICIAR EL TRAMITE",
        "geo_puntos": [],  # short URL
    },
    {
        "tipo": "exp",
        "nombre": "ALMAFUERTE",
        "localidad_nombre": "Almafuerte",
        "expediente": None,
        "superficie": None,
        "lotes": 1200,
        "ejuridico": E_SIN_INICIAR,
        "etecnico": E_DIR_REG_OBRAS,
        "efinanciero": E_SIN_INICIAR,
        "monto": Decimal("20021309586.15"),
        "valor_fiscal": Decimal("2016391989.35"),
        "infra_sin_nexos": Decimal("17400000000.00"),
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": Decimal("20021309586.15"),
        "obs": "Ver q parcelas quedan (sin linea de alta tension + arroyo)",
        "geo_puntos": [
            {"lat": Decimal("-32.170320"), "lng": Decimal("-64.217973")},
            {"lat": Decimal("-32.175459"), "lng": Decimal("-64.218578")},
            {"lat": Decimal("-32.175691"), "lng": Decimal("-64.217914")},
            {"lat": Decimal("-32.175542"), "lng": Decimal("-64.216977")},
        ],
    },
    {
        "tipo": "exp",
        "nombre": "VILLA MARIA",
        "localidad_nombre": "Villa Maria",
        "expediente": "0921-221254/2026",
        "superficie": Decimal("105.21"),
        "lotes": 1744,
        "ejuridico": E_LEGALES_RESOLUCION,
        "etecnico": E_COMPLETADO,
        "efinanciero": E_MIN_ECONOMIA,
        "monto": Decimal("40667932721.47"),
        "valor_fiscal": Decimal("3848546670.36"),
        "infra_sin_nexos": Decimal("25288000000.00"),
        "costo_nexos": Decimal("10376822050.00"),
        "convenio_unc": None,
        "costo_total_infra": Decimal("40667932721.47"),
        "obs": "Parcela 5 y Parcela 6",
        "geo_puntos": [
            {"lat": Decimal("-32.400594"), "lng": Decimal("-63.206245")},
            {"lat": Decimal("-32.406309"), "lng": Decimal("-63.209271")},
        ],
    },
    {
        "tipo": "exp",
        "nombre": "MONTECRISTO",
        "localidad_nombre": "Montecristo",
        "expediente": None,
        "superficie": Decimal("39.52"),
        "lotes": 987,
        "ejuridico": E_NOTA_MCYM,
        "etecnico": E_DIR_REG_OBRAS,
        "efinanciero": E_SIN_INICIAR,
        "monto": Decimal("15066798517.55"),
        "valor_fiscal": Decimal("580998859.65"),
        "infra_sin_nexos": Decimal("14311500000.00"),
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": Decimal("15066798517.55"),
        "obs": None,
        "geo_puntos": [
            {"lat": Decimal("-31.324766"), "lng": Decimal("-63.853769")},
            {"lat": Decimal("-31.328559"), "lng": Decimal("-63.853769")},
            {"lat": Decimal("-31.320058"), "lng": Decimal("-63.847348")},
            {"lat": Decimal("-31.317361"), "lng": Decimal("-63.849060")},
        ],
    },
    {
        "tipo": "exp",
        "nombre": "LAS HIGUERAS",
        "localidad_nombre": "Las Higueras",
        "expediente": "0135-045959/2026",
        "superficie": None,
        "lotes": 78,
        "ejuridico": E_LEGALES_RESOLUCION,
        "etecnico": E_COMPLETADO,
        "efinanciero": E_MIN_ECONOMIA,
        "monto": Decimal("1716218354.97"),
        "valor_fiscal": Decimal("450167965.36"),
        "infra_sin_nexos": Decimal("1131000000.00"),
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": Decimal("1716218354.97"),
        "obs": "Para NP 31/7",
        "geo_puntos": [
            {"lat": Decimal("-33.088414"), "lng": Decimal("-64.299660")},
            {"lat": Decimal("-33.088787"), "lng": Decimal("-64.298952")},
        ],
    },
    {
        "tipo": "exp",
        "nombre": "RIO CUARTO",
        "localidad_nombre": "Rio Cuarto",
        "expediente": "0404-001344/2026",
        "superficie": Decimal("54.09"),
        "lotes": 1352,
        "ejuridico": E_LEGALES_RESOLUCION,
        "etecnico": E_COMPLETADO,
        "efinanciero": E_MIN_ECONOMIA,
        "monto": Decimal("36071202227.47"),
        "valor_fiscal": Decimal("4034001713.44"),
        "infra_sin_nexos": Decimal("19604000000.00"),
        "costo_nexos": Decimal("11223000000.00"),
        "convenio_unc": None,
        "costo_total_infra": Decimal("36071202227.47"),
        "obs": "Para NP 31/7",
        "geo_puntos": [
            {"lat": Decimal("-33.085517"), "lng": Decimal("-64.350984")},
            {"lat": Decimal("-33.083602"), "lng": Decimal("-64.343844")},
            {"lat": Decimal("-33.083235"), "lng": Decimal("-64.346725")},
            {"lat": Decimal("-33.085937"), "lng": Decimal("-64.344595")},
        ],
    },
    {
        "tipo": "exp",
        "nombre": "CRUZ DEL EJE",
        "localidad_nombre": "Cruz del Eje",
        "expediente": "GOBDIGI-0584468111-926",
        "superficie": None,
        "lotes": 1424,
        "ejuridico": E_INTERVENCION_INFRA,
        "etecnico": E_INFORME_PREFACT,
        "efinanciero": E_SIN_INICIAR,
        "monto": Decimal("21482899417.27"),
        "valor_fiscal": Decimal("642230320.98"),
        "infra_sin_nexos": Decimal("20648000000.00"),
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": Decimal("21482899417.27"),
        "obs": None,
        "geo_puntos": [
            {"lat": Decimal("-30.734050"), "lng": Decimal("-64.807832")},
            {"lat": Decimal("-30.734096"), "lng": Decimal("-64.806895")},
            {"lat": Decimal("-30.735820"), "lng": Decimal("-64.810534")},
            {"lat": Decimal("-30.735522"), "lng": Decimal("-64.812192")},
            {"lat": Decimal("-30.736855"), "lng": Decimal("-64.815617")},
            {"lat": Decimal("-30.737982"), "lng": Decimal("-64.818185")},
            {"lat": Decimal("-30.734533"), "lng": Decimal("-64.814172")},
            {"lat": Decimal("-30.736855"), "lng": Decimal("-64.819549")},
            {"lat": Decimal("-30.737775"), "lng": Decimal("-64.821368")},
            {"lat": Decimal("-30.738442"), "lng": Decimal("-64.823081")},
            {"lat": Decimal("-30.733623"), "lng": Decimal("-64.815183")},
            {"lat": Decimal("-30.732933"), "lng": Decimal("-64.815341")},
        ],
    },
    {
        "tipo": "exp",
        "nombre": "SALSIPUEDES",
        "localidad_nombre": "Salsipuedes",
        "expediente": None,
        "superficie": Decimal("4.6457"),
        "lotes": 140,
        "ejuridico": E_SIN_INICIAR,
        "etecnico": E_DIR_REG_OBRAS,
        "efinanciero": E_SIN_INICIAR,
        "monto": Decimal("2175606152.99"),
        "valor_fiscal": Decimal("112004733.07"),
        "infra_sin_nexos": Decimal("2030000000.00"),
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": Decimal("2175606152.99"),
        "obs": None,
        "geo_puntos": [
            {"lat": Decimal("-31.139673"), "lng": Decimal("-64.264617")},
            {"lat": Decimal("-31.140230"), "lng": Decimal("-64.263051")},
            {"lat": Decimal("-31.139702"), "lng": Decimal("-64.262457")},
            {"lat": Decimal("-31.139096"), "lng": Decimal("-64.262388")},
            {"lat": Decimal("-31.138225"), "lng": Decimal("-64.262811")},
        ],
    },
    {
        "tipo": "exp",
        "nombre": "ESTACION JUAREZ CELMAN II",
        "localidad_nombre": "Estacion Juarez Celman",
        "expediente": "0990632111626",
        "superficie": None,
        "lotes": 292,
        "ejuridico": E_INTERVENCION_INFRA,
        "etecnico": E_INFORME_PREFACT,
        "efinanciero": E_SIN_INICIAR,
        "monto": Decimal("4234000000.00"),
        "valor_fiscal": None,
        "infra_sin_nexos": Decimal("4234000000.00"),
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": Decimal("4234000000.00"),
        "obs": None,
        "geo_puntos": [
            {"lat": Decimal("-31.300262"), "lng": Decimal("-64.183370")},
        ],
    },
    {
        "tipo": "exp",
        "nombre": "SALSIPUEDES II",
        "localidad_nombre": "Salsipuedes",
        "expediente": None,
        "superficie": None,
        "lotes": None,
        "ejuridico": E_SIN_INICIAR,
        "etecnico": E_SIN_INICIAR,
        "efinanciero": E_SIN_INICIAR,
        "monto": None,
        "valor_fiscal": None,
        "infra_sin_nexos": None,
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": None,
        "obs": "6/7 Villa Sol ver si los lotes son APTOS para la expropiacion",
        "geo_puntos": [],
    },
    {
        "tipo": "exp",
        "nombre": "VILLA MARIA II",
        "localidad_nombre": "Villa Maria",
        "expediente": None,
        "superficie": Decimal("25"),
        "lotes": 625,
        "ejuridico": E_SIN_INICIAR,
        "etecnico": E_SIN_INICIAR,
        "efinanciero": E_SIN_INICIAR,
        "monto": Decimal("9062500000.00"),
        "valor_fiscal": None,
        "infra_sin_nexos": Decimal("9062500000.00"),
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": Decimal("9062500000.00"),
        "obs": "078823711160026 CANCELACION DE UNA EXPROP. DE VA MARIA / 078823511184026",
        "geo_puntos": [],
    },
    {
        "tipo": "exp",
        "nombre": "CAPITAL - INGRESO RUTA 19 NORTE",
        "localidad_nombre": "Cordoba",
        "expediente": None,
        "superficie": None,
        "lotes": 1000,
        "ejuridico": E_INTERVENCION_INFRA,
        "etecnico": E_SIN_INICIAR,
        "efinanciero": E_SIN_INICIAR,
        "monto": Decimal("14500000000.00"),
        "valor_fiscal": None,
        "infra_sin_nexos": Decimal("14500000000.00"),
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": Decimal("14500000000.00"),
        "obs": None,
        "geo_puntos": [
            {"lat": Decimal("-31.396524"), "lng": Decimal("-64.133293")},
        ],
    },
    {
        "tipo": "exp",
        "nombre": "CAPITAL - INGRESO RUTA 19 SUR",
        "localidad_nombre": "Cordoba",
        "expediente": None,
        "superficie": None,
        "lotes": 422,
        "ejuridico": E_INTERVENCION_INFRA,
        "etecnico": E_SIN_INICIAR,
        "efinanciero": E_SIN_INICIAR,
        "monto": Decimal("6119000000.00"),
        "valor_fiscal": None,
        "infra_sin_nexos": Decimal("6119000000.00"),
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": Decimal("6119000000.00"),
        "obs": None,
        "geo_puntos": [
            {"lat": Decimal("-31.399412"), "lng": Decimal("-64.134957")},
        ],
    },
    {
        "tipo": "exp",
        "nombre": "CAPITAL - VILLA RETIRO SUR",
        "localidad_nombre": "Cordoba",
        "expediente": None,
        "superficie": None,
        "lotes": 1310,
        "ejuridico": E_INTERVENCION_INFRA,
        "etecnico": E_SIN_INICIAR,
        "efinanciero": E_SIN_INICIAR,
        "monto": Decimal("18995000000.00"),
        "valor_fiscal": None,
        "infra_sin_nexos": Decimal("18995000000.00"),
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": Decimal("18995000000.00"),
        "obs": None,
        "geo_puntos": [
            {"lat": Decimal("-31.354369"), "lng": Decimal("-64.135832")},
        ],
    },
    {
        "tipo": "exp",
        "nombre": "CAPITAL - VILLA BOEDO",
        "localidad_nombre": "Cordoba",
        "expediente": None,
        "superficie": None,
        "lotes": 2500,
        "ejuridico": E_INTERVENCION_INFRA,
        "etecnico": E_SIN_INICIAR,
        "efinanciero": E_SIN_INICIAR,
        "monto": Decimal("36250000000.00"),
        "valor_fiscal": None,
        "infra_sin_nexos": Decimal("36250000000.00"),
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": Decimal("36250000000.00"),
        "obs": None,
        "geo_puntos": [
            {"lat": Decimal("-31.471989"), "lng": Decimal("-64.074623")},
        ],
    },
    {
        "tipo": "exp",
        "nombre": "CAPITAL - FERREYRA",
        "localidad_nombre": "Cordoba",
        "expediente": None,
        "superficie": None,
        "lotes": 2725,
        "ejuridico": E_INTERVENCION_INFRA,
        "etecnico": E_SIN_INICIAR,
        "efinanciero": E_SIN_INICIAR,
        "monto": Decimal("39512500000.00"),
        "valor_fiscal": None,
        "infra_sin_nexos": Decimal("39512500000.00"),
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": Decimal("39512500000.00"),
        "obs": None,
        "geo_puntos": [
            {"lat": Decimal("-31.472693"), "lng": Decimal("-64.106398")},
        ],
    },
    {
        "tipo": "exp",
        "nombre": "CAPITAL - PARQUE DEL ESTE O.S.N.",
        "localidad_nombre": "Cordoba",
        "expediente": None,
        "superficie": None,
        "lotes": 372,
        "ejuridico": E_INTERVENCION_INFRA,
        "etecnico": E_SIN_INICIAR,
        "efinanciero": E_SIN_INICIAR,
        "monto": Decimal("5394000000.00"),
        "valor_fiscal": None,
        "infra_sin_nexos": Decimal("5394000000.00"),
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": Decimal("5394000000.00"),
        "obs": 'Terrenos de la Municipalidad para "donar a la Provincia"',
        "geo_puntos": [
            {"lat": Decimal("-31.401346"), "lng": Decimal("-64.145695")},
        ],
    },
    {
        "tipo": "exp",
        "nombre": "CAPITAL - SAN FELIPE",
        "localidad_nombre": "Cordoba",
        "expediente": None,
        "superficie": None,
        "lotes": 188,
        "ejuridico": E_INTERVENCION_INFRA,
        "etecnico": E_SIN_INICIAR,
        "efinanciero": E_SIN_INICIAR,
        "monto": Decimal("2726000000.00"),
        "valor_fiscal": None,
        "infra_sin_nexos": Decimal("2726000000.00"),
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": Decimal("2726000000.00"),
        "obs": 'Terrenos de la Municipalidad para "donar a la Provincia"',
        "geo_puntos": [
            {"lat": Decimal("-31.456704"), "lng": Decimal("-64.137224")},
        ],
    },
    {
        "tipo": "exp",
        "nombre": "CAPITAL - VILLA EL LIBERTADOR",
        "localidad_nombre": "Cordoba",
        "expediente": None,
        "superficie": None,
        "lotes": 142,
        "ejuridico": E_INTERVENCION_INFRA,
        "etecnico": E_SIN_INICIAR,
        "efinanciero": E_SIN_INICIAR,
        "monto": Decimal("2059000000.00"),
        "valor_fiscal": None,
        "infra_sin_nexos": Decimal("2059000000.00"),
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": Decimal("2059000000.00"),
        "obs": "2 parcelas",
        "geo_puntos": [
            {"lat": Decimal("-31.481066"), "lng": Decimal("-64.218334")},
        ],
    },

    # ── CONVENIOS CON MUNICIPIOS (15) ────────────────────────────────────────
    {
        "tipo": "muni",
        "nombre": "Suco",
        "localidad_nombre": "Suco",
        "expediente": "0921-222432/2026",
        "superficie": None,
        "lotes": 28,
        "ejuridico": E_SIN_INICIAR,
        "etecnico": E_PASE_SEC_GESTION,
        "efinanciero": E_SIN_INICIAR,
        "monto": None,
        "valor_fiscal": None,
        "infra_sin_nexos": None,
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": None,
        "obs": "la nota se encuentra la la Sec de Gestion y Vinculacion de Infraestructura",
        "geo_puntos": [],
    },
    {
        "tipo": "muni",
        "nombre": "SANTA CATALINA",
        "localidad_nombre": "Santa Catalina Holmberg",
        "expediente": "0886386111026",
        "superficie": None,
        "lotes": 100,
        "ejuridico": E_SIN_INICIAR,
        "etecnico": E_SIN_INICIAR,
        "efinanciero": E_SIN_INICIAR,
        "monto": None,
        "valor_fiscal": None,
        "infra_sin_nexos": None,
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": None,
        "obs": "nota el la Privada de Vivienda",
        "geo_puntos": [],
    },
    {
        "tipo": "muni",
        "nombre": "Colonia Caroya",
        "localidad_nombre": "Colonia Caroya",
        "expediente": None,
        "superficie": None,
        "lotes": None,
        "ejuridico": E_SIN_INICIAR,
        "etecnico": E_SIN_INICIAR,
        "efinanciero": E_SIN_INICIAR,
        "monto": None,
        "valor_fiscal": None,
        "infra_sin_nexos": None,
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": None,
        "obs": None,
        "geo_puntos": [],
    },
    {
        "tipo": "muni",
        "nombre": "Cintra",
        "localidad_nombre": "Cintra",
        "expediente": None,
        "superficie": None,
        "lotes": None,
        "ejuridico": E_SIN_INICIAR,
        "etecnico": E_SIN_INICIAR,
        "efinanciero": E_SIN_INICIAR,
        "monto": None,
        "valor_fiscal": None,
        "infra_sin_nexos": None,
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": None,
        "obs": None,
        "geo_puntos": [],
    },
    {
        "tipo": "muni",
        "nombre": "Corral de Bustos",
        "localidad_nombre": "Corral de Bustos",
        "expediente": None,
        "superficie": None,
        "lotes": 81,
        "ejuridico": E_SIN_INICIAR,
        "etecnico": E_SIN_INICIAR,
        "efinanciero": E_SIN_INICIAR,
        "monto": None,
        "valor_fiscal": None,
        "infra_sin_nexos": None,
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": None,
        "obs": "ver prefactibilidad - rastrear nota\nMe comunico con el Intendente",
        "geo_puntos": [],
    },
    {
        "tipo": "muni",
        "nombre": "Las Tapias",
        "localidad_nombre": "Las Tapias",
        "expediente": None,
        "superficie": None,
        "lotes": None,
        "ejuridico": E_SIN_INICIAR,
        "etecnico": E_SIN_INICIAR,
        "efinanciero": E_SIN_INICIAR,
        "monto": None,
        "valor_fiscal": None,
        "infra_sin_nexos": None,
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": None,
        "obs": None,
        "geo_puntos": [],
    },
    {
        "tipo": "muni",
        "nombre": "Dean Funes",
        "localidad_nombre": "Dean Funes",
        "expediente": None,
        "superficie": None,
        "lotes": None,
        "ejuridico": E_SIN_INICIAR,
        "etecnico": E_SIN_INICIAR,
        "efinanciero": E_SIN_INICIAR,
        "monto": None,
        "valor_fiscal": None,
        "infra_sin_nexos": None,
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": None,
        "obs": None,
        "geo_puntos": [],
    },
    {
        "tipo": "muni",
        "nombre": "Estacion Gral. Paz",
        "localidad_nombre": "Estacion General Paz",
        "expediente": None,
        "superficie": None,
        "lotes": None,
        "ejuridico": E_SIN_INICIAR,
        "etecnico": E_SIN_INICIAR,
        "efinanciero": E_SIN_INICIAR,
        "monto": None,
        "valor_fiscal": None,
        "infra_sin_nexos": None,
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": None,
        "obs": None,
        "geo_puntos": [],
    },
    {
        "tipo": "muni",
        "nombre": "Embalse",
        "localidad_nombre": "Embalse",
        "expediente": "100077311178826",
        "superficie": None,
        "lotes": None,
        "ejuridico": E_SIN_INICIAR,
        "etecnico": E_SIN_INICIAR,
        "efinanciero": E_SIN_INICIAR,
        "monto": None,
        "valor_fiscal": None,
        "infra_sin_nexos": None,
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": None,
        "obs": None,
        "geo_puntos": [],
    },
    {
        "tipo": "muni",
        "nombre": "MALAGUEÑO",
        "localidad_nombre": "Malagueño",
        "expediente": None,
        "superficie": None,
        "lotes": 634,
        "ejuridico": E_SIN_INICIAR,
        "etecnico": E_SIN_INICIAR,
        "efinanciero": E_SIN_INICIAR,
        "monto": None,
        "valor_fiscal": None,
        "infra_sin_nexos": None,
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": None,
        "obs": "25 ha + Triangulo (5ha) + Espacio Verde IPV",
        "geo_puntos": [],
    },
    {
        "tipo": "muni",
        "nombre": "TOSQUITA",
        "localidad_nombre": "Tosquita",
        "expediente": None,
        "superficie": None,
        "lotes": 30,
        "ejuridico": E_SIN_INICIAR,
        "etecnico": E_SIN_INICIAR,
        "efinanciero": E_SIN_INICIAR,
        "monto": None,
        "valor_fiscal": None,
        "infra_sin_nexos": None,
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": None,
        "obs": "Me contacto con Intendente para que mande INFO - Sin Presentación FORMAL",
        "geo_puntos": [],
    },
    {
        "tipo": "muni",
        "nombre": "LAS VERTIENTES",
        "localidad_nombre": "Las Vertientes",
        "expediente": None,
        "superficie": None,
        "lotes": 30,
        "ejuridico": E_SIN_INICIAR,
        "etecnico": E_SIN_INICIAR,
        "efinanciero": E_SIN_INICIAR,
        "monto": None,
        "valor_fiscal": None,
        "infra_sin_nexos": None,
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": None,
        "obs": "Comunicación con el Intendente para que mande INFO\nEl Intendente se ha comunicado con la Privada del Ministro Brandan",
        "geo_puntos": [],
    },
    {
        "tipo": "muni",
        "nombre": "EL TIO",
        "localidad_nombre": "El Tio",
        "expediente": "060757511132426",
        "superficie": None,
        "lotes": None,
        "ejuridico": E_SIN_INICIAR,
        "etecnico": E_SIN_INICIAR,
        "efinanciero": E_SIN_INICIAR,
        "monto": None,
        "valor_fiscal": None,
        "infra_sin_nexos": None,
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": None,
        "obs": "Para OK de los Ministros\nDoc Tecnica en Revisión",
        "geo_puntos": [],
    },
    {
        "tipo": "muni",
        "nombre": "El Manzano",
        "localidad_nombre": "El Manzano",
        "expediente": None,
        "superficie": None,
        "lotes": None,
        "ejuridico": E_SIN_INICIAR,
        "etecnico": E_SIN_INICIAR,
        "efinanciero": E_SIN_INICIAR,
        "monto": None,
        "valor_fiscal": None,
        "infra_sin_nexos": None,
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": None,
        "obs": "me comunique con el Intendente para q presente la nota",
        "geo_puntos": [],
    },
    {
        "tipo": "muni",
        "nombre": "Las Higueras - CISTERNA",
        "localidad_nombre": "Las Higueras",
        "expediente": None,
        "superficie": None,
        "lotes": None,
        "ejuridico": E_SIN_INICIAR,
        "etecnico": E_SIN_INICIAR,
        "efinanciero": E_SIN_INICIAR,
        "monto": Decimal("400000000.00"),
        "valor_fiscal": None,
        "infra_sin_nexos": None,
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": None,
        "obs": "a la espera de la documentación técnica",
        "geo_puntos": [],
    },

    # ── LOTES PROVINCIALES (13) ──────────────────────────────────────────────
    {
        "tipo": "prov",
        "nombre": "Villa Dolores",
        "localidad_nombre": "Villa Dolores",
        "expediente": None,
        "superficie": None,
        "lotes": 514,
        "ejuridico": E_SIN_INICIAR,
        "etecnico": E_COMPLETADO,
        "efinanciero": E_SIN_INICIAR,
        "monto": Decimal("4064335126.70"),
        "valor_fiscal": None,
        "infra_sin_nexos": Decimal("7453000000.00"),
        "costo_nexos": Decimal("1503145818.00"),
        "convenio_unc": None,
        "costo_total_infra": Decimal("8956145818.00"),
        "obs": "490 lotes 24 lotes",
        "geo_puntos": [
            {"lat": Decimal("-31.959460"), "lng": Decimal("-65.208438")},
            {"lat": Decimal("-31.951321"), "lng": Decimal("-65.203648")},
        ],
    },
    {
        "tipo": "prov",
        "nombre": "Villa de Maria",
        "localidad_nombre": "Villa de Maria de Rio Seco",
        "expediente": "GOBDIGI-0876656111-026",
        "superficie": None,
        "lotes": 205,
        "ejuridico": E_SIN_INICIAR,
        "etecnico": E_SIN_INICIAR,
        "efinanciero": E_SIN_INICIAR,
        "monto": Decimal("4679068800.00"),
        "valor_fiscal": None,
        "infra_sin_nexos": Decimal("2972500000.00"),
        "costo_nexos": Decimal("587274310.76"),
        "convenio_unc": None,
        "costo_total_infra": Decimal("3559774310.76"),
        "obs": None,
        "geo_puntos": [
            {"lat": Decimal("-29.900071"), "lng": Decimal("-63.732923")},
        ],
    },
    {
        "tipo": "prov",
        "nombre": "Oliva",
        "localidad_nombre": "Oliva",
        "expediente": "GOBDIGI-0876322111-026",
        "superficie": None,
        "lotes": 424,
        "ejuridico": E_SIN_INICIAR,
        "etecnico": E_SIN_INICIAR,
        "efinanciero": E_SIN_INICIAR,
        "monto": Decimal("9957427200.00"),
        "valor_fiscal": None,
        "infra_sin_nexos": Decimal("6148000000.00"),
        "costo_nexos": Decimal("1214655159.82"),
        "convenio_unc": None,
        "costo_total_infra": Decimal("7362655159.82"),
        "obs": None,
        "geo_puntos": [
            {"lat": Decimal("-32.050330"), "lng": Decimal("-63.547185")},
        ],
    },
    {
        "tipo": "prov",
        "nombre": "Bell Ville",
        "localidad_nombre": "Bell Ville",
        "expediente": "GOBDIGI-0874264111-726",
        "superficie": None,
        "lotes": 409,
        "ejuridico": E_SIN_INICIAR,
        "etecnico": E_SIN_INICIAR,
        "efinanciero": E_SIN_INICIAR,
        "monto": Decimal("10191347712.00"),
        "valor_fiscal": None,
        "infra_sin_nexos": Decimal("5930500000.00"),
        "costo_nexos": Decimal("1757525803.18"),
        "convenio_unc": None,
        "costo_total_infra": Decimal("7688025803.18"),
        "obs": "Se debe realizar una BATIMETRIA para poder definir el proyecto",
        "geo_puntos": [
            {"lat": Decimal("-32.615568"), "lng": Decimal("-62.705587")},
        ],
    },
    {
        "tipo": "prov",
        "nombre": "Villa de Soto",
        "localidad_nombre": "Villa de Soto",
        "expediente": "GOBDIGI-0934075111-026",
        "superficie": None,
        "lotes": 95,
        "ejuridico": E_SIN_INICIAR,
        "etecnico": E_SIN_INICIAR,
        "efinanciero": E_SIN_INICIAR,
        "monto": Decimal("2097513600.00"),
        "valor_fiscal": None,
        "infra_sin_nexos": Decimal("1377500000.00"),
        "costo_nexos": Decimal("272151509.86"),
        "convenio_unc": None,
        "costo_total_infra": Decimal("1649651509.86"),
        "obs": None,
        "geo_puntos": [
            {"lat": Decimal("-30.867437"), "lng": Decimal("-64.988635")},
        ],
    },
    {
        "tipo": "prov",
        "nombre": "Santa Teresa",
        "localidad_nombre": "Santa Teresa",
        "expediente": None,
        "superficie": None,
        "lotes": 22,
        "ejuridico": E_SIN_INICIAR,
        "etecnico": E_SIN_INICIAR,
        "efinanciero": E_SIN_INICIAR,
        "monto": Decimal("5157844192.00"),
        "valor_fiscal": None,
        "infra_sin_nexos": None,
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": None,
        "obs": "Idea de pasar para que lo haga Ing Bande",
        "geo_puntos": [],
    },
    {
        "tipo": "prov",
        "nombre": "Malagueño",
        "localidad_nombre": "Malagueño",
        "expediente": None,
        "superficie": None,
        "lotes": 76,
        "ejuridico": E_SIN_INICIAR,
        "etecnico": E_SIN_INICIAR,
        "efinanciero": E_SIN_INICIAR,
        "monto": Decimal("1501516800.00"),
        "valor_fiscal": None,
        "infra_sin_nexos": None,
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": None,
        "obs": "Idea pasarselo al Ing Bande",
        "geo_puntos": [],
    },
    {
        "tipo": "prov",
        "nombre": "Almafuerte",
        "localidad_nombre": "Almafuerte",
        "expediente": None,
        "superficie": None,
        "lotes": 22,
        "ejuridico": E_SIN_INICIAR,
        "etecnico": E_SIN_INICIAR,
        "efinanciero": E_SIN_INICIAR,
        "monto": Decimal("405672960.00"),
        "valor_fiscal": None,
        "infra_sin_nexos": None,
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": None,
        "obs": "Idea pasarselo al Ing Bande",
        "geo_puntos": [],
    },
    {
        "tipo": "prov",
        "nombre": "Idiazabal",
        "localidad_nombre": "Idiazabal",
        "expediente": None,
        "superficie": None,
        "lotes": 20,
        "ejuridico": E_SIN_INICIAR,
        "etecnico": E_SIN_INICIAR,
        "efinanciero": E_SIN_INICIAR,
        "monto": Decimal("368793600.00"),
        "valor_fiscal": None,
        "infra_sin_nexos": None,
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": None,
        "obs": "Idea pasarselo al Ing Bande",
        "geo_puntos": [],
    },
    {
        "tipo": "prov",
        "nombre": "Chingolo",
        "localidad_nombre": "Barrio Chingolo",
        "expediente": None,
        "superficie": None,
        "lotes": 358,
        "ejuridico": E_SIN_INICIAR,
        "etecnico": E_SIN_INICIAR,
        "efinanciero": E_SIN_INICIAR,
        "monto": None,
        "valor_fiscal": None,
        "infra_sin_nexos": None,
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": None,
        "obs": None,
        "geo_puntos": [],
    },
    {
        "tipo": "prov",
        "nombre": "Villa Dolores II",
        "localidad_nombre": "Villa Dolores",
        "expediente": None,
        "superficie": None,
        "lotes": None,
        "ejuridico": E_SIN_INICIAR,
        "etecnico": E_SIN_INICIAR,
        "efinanciero": E_SIN_INICIAR,
        "monto": None,
        "valor_fiscal": None,
        "infra_sin_nexos": None,
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": None,
        "obs": None,
        "geo_puntos": [],
    },
    {
        "tipo": "prov",
        "nombre": "Villa Dolores - LUZ",
        "localidad_nombre": "Villa Dolores",
        "expediente": None,
        "superficie": None,
        "lotes": None,
        "ejuridico": E_SIN_INICIAR,
        "etecnico": E_COMPLETADO,
        "efinanciero": E_SIN_INICIAR,
        "monto": Decimal("2395429778.17"),
        "valor_fiscal": None,
        "infra_sin_nexos": None,
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": None,
        "obs": "Contratacion Directa",
        "geo_puntos": [],
    },
    {
        "tipo": "prov",
        "nombre": "Villa Dolores - AGUA",
        "localidad_nombre": "Villa Dolores",
        "expediente": None,
        "superficie": None,
        "lotes": None,
        "ejuridico": E_SIN_INICIAR,
        "etecnico": E_COMPLETADO,
        "efinanciero": E_SIN_INICIAR,
        "monto": Decimal("5214006256.84"),
        "valor_fiscal": None,
        "infra_sin_nexos": None,
        "costo_nexos": None,
        "convenio_unc": None,
        "costo_total_infra": None,
        "obs": "Contratacion Directa",
        "geo_puntos": [],
    },
]
