# Datos migrados del Panel_Cordon_Cuneta.html (46 municipios)
# Fuente: Panel_Cordon_Cuneta.html — datos al momento de la migración (jun 2026)
MUNICIPIOS_SEED = [
    {"municipio": "Alcira Gigena", "departamento": "Río Cuarto", "ok_ministerio": True},
    {"municipio": "Alicia", "departamento": "San Justo", "ok_ministerio": True},
    {"municipio": "Almafuerte", "departamento": "Tercero Arriba", "ok_ministerio": True},
    {"municipio": "Alta Gracia", "departamento": "Santa María", "ok_ministerio": True},
    {"municipio": "Arroyito", "departamento": "San Justo", "ok_ministerio": True},
    {"municipio": "Bell Ville", "departamento": "Unión", "ok_ministerio": True},
    {"municipio": "Berrotarán", "departamento": "Río Cuarto", "ok_ministerio": True},
    {"municipio": "Brinkmann", "departamento": "San Justo", "ok_ministerio": True},
    {"municipio": "Capilla del Monte", "departamento": "Punilla", "ok_ministerio": True},
    {"municipio": "Corral de Bustos", "departamento": "Marcos Juárez", "ok_ministerio": True},
    {"municipio": "Cruz Alta", "departamento": "Marcos Juárez", "ok_ministerio": True},
    {"municipio": "Cruz del Eje", "departamento": "Cruz del Eje", "ok_ministerio": True},
    {"municipio": "Dean Funes", "departamento": "Ischilín", "ok_ministerio": True},
    {"municipio": "General Cabrera", "departamento": "Juárez Celman", "ok_ministerio": True},
    {"municipio": "General Deheza", "departamento": "Juárez Celman", "ok_ministerio": True},
    {"municipio": "Hernando", "departamento": "Tercero Arriba", "ok_ministerio": True},
    {"municipio": "Huinca Renancó", "departamento": "General Roca", "ok_ministerio": True},
    {"municipio": "Jesús María", "departamento": "Colón", "ok_ministerio": True},
    {"municipio": "La Carlota", "departamento": "Juárez Celman", "ok_ministerio": True},
    {"municipio": "La Falda", "departamento": "Punilla", "ok_ministerio": True},
    {"municipio": "Laboulaye", "departamento": "Presidente Roque Sáenz Peña", "ok_ministerio": True},
    {"municipio": "Las Varillas", "departamento": "San Justo", "ok_ministerio": True},
    {"municipio": "Leones", "departamento": "Marcos Juárez", "ok_ministerio": True},
    {"municipio": "Luque", "departamento": "Tercero Arriba", "ok_ministerio": True},
    {"municipio": "Marcos Juárez", "departamento": "Marcos Juárez", "ok_ministerio": True},
    {"municipio": "Mina Clavero", "departamento": "San Alberto", "ok_ministerio": True},
    {"municipio": "Monte Maíz", "departamento": "Unión", "ok_ministerio": True},
    {"municipio": "Morteros", "departamento": "San Justo", "ok_ministerio": True},
    {"municipio": "Oliva", "departamento": "Tercero Arriba", "ok_ministerio": True},
    {"municipio": "Oncativo", "departamento": "Río Segundo", "ok_ministerio": True},
    {"municipio": "Porteña", "departamento": "San Justo", "ok_ministerio": True},
    {"municipio": "Río Ceballos", "departamento": "Colón", "ok_ministerio": True},
    {"municipio": "Río Cuarto", "departamento": "Río Cuarto", "ok_ministerio": True},
    {"municipio": "Río Segundo", "departamento": "Río Segundo", "ok_ministerio": True},
    {"municipio": "Río Tercero", "departamento": "Tercero Arriba", "ok_ministerio": True},
    {"municipio": "Rufino", "departamento": None, "ok_ministerio": True},
    {"municipio": "Sacanta", "departamento": "San Justo", "ok_ministerio": True},
    {"municipio": "San Francisco", "departamento": "San Justo", "ok_ministerio": True},
    {"municipio": "San Jorge", "departamento": "San Justo", "ok_ministerio": True},
    {"municipio": "Tancacha", "departamento": "Río Cuarto", "ok_ministerio": True},
    {"municipio": "Unquillo", "departamento": "Colón", "ok_ministerio": True},
    {"municipio": "Villa Carlos Paz", "departamento": "Punilla", "ok_ministerio": True},
    {"municipio": "Villa Cura Brochero", "departamento": "San Alberto", "ok_ministerio": True},
    {"municipio": "Villa del Rosario", "departamento": "Río Segundo", "ok_ministerio": True},
    {"municipio": "Villa Dolores", "departamento": "San Javier", "ok_ministerio": True},
    {"municipio": "Villa María", "departamento": "General San Martín", "ok_ministerio": True},
]
